### PR TITLE
add plural form for -ad, -iz

### PR DESCRIPTION
**Pull request by tornoz**

### CODE REVIEW

**Comment by Wanibzh29** [comment]
Could be also sing: -ad, plural: -idi, maybe a p9?

**Comment by tornoz** [comment]
good call! it is added

**Comment by Wanibzh29** [comment]
I have seen how the plural form "-ion" and "-ien" were separated do you think that they could be merged?

**Comment by tornoz** [comment]
> I have seen how the plural form "-ion" and "-ien" were separated do you think that they could be merged?

That seems like a good idea but the .dic file would have to be changed to match with the new tags so that should be done in a new PR

**Pull request merged**
